Repository openmfp/portal-ui-lib, pull requests merged in 2025-09, with the labels that each got.

#418 feat: remove organization comp & UserProfileConfigServiceImpl
  projects/lib/src/lib/portal-providers.ts
  projects/lib/src/lib/services/luigi-config/user-profile-config.service.ts
  projects/lib/src/lib/services/luigi-nodes/nodes-processing.service.spec.ts
  projects/wc/src/app/components/organization-management/organization-management.component.html
  projects/wc/src/app/components/organization-management/organization-management.component.scss
  projects/wc/src/app/components/organization-management/organization-management.component.spec.ts
  projects/wc/src/app/components/organization-management/organization-management.component.ts
  projects/wc/src/app/initializers/luigi-wc-initializer.spec.ts
  projects/wc/src/app/initializers/luigi-wc-initializer.ts
Labels: enhancement

#425 feat: remove generic-ui from docs
  README.md
  docs/readme-generic-ui.md
Labels: documentation

#442 fix the feature toggle usage
  projects/lib/src/lib/components/luigi/luigi.component.spec.ts
  projects/lib/src/lib/components/luigi/luigi.component.ts
  projects/lib/src/lib/services/luigi-config/lifecycle-hooks-config.service.ts
  projects/lib/src/lib/services/luigi-config/static-settings-config.service.ts
Labels: bug
